### ISSUE TITLE
`optional (nullable a)` is not representable

### ISSUE THREAD

**Issue by kanwren** [chessai/nix-std#12]
`optional`'s new indirection allows for nesting `optional`s (e.g. `optional (optional int)`), but since it's just a wrapper over `nullable`, the element type itself cannot be nullable. This causes bad properties such as the following:

```
nix-repl> optional.isNothing (optional.just null)
true
```

This could be fixed by actually tagging the set, like `{ _tag = "nothing"; }` for Nothing and `{ _tag = "just"; value = 5; }` for Just.

**Comment by chessai** [comment]
I thought a tag might be necessary. Dang.

**Comment by kanwren** [comment]
addressed by 30fb845a4329971e0b9f1fdee79e045e5558d654 and #16
