### ISSUE TITLE
`sin`/`cos` are very innacurate for values far from origin

### ISSUE THREAD

**Issue by kanwren** [chessai/nix-std#14]
Because the `sin`/`cos` in `num.nix` use a Taylor approximation, they quickly become inaccurate the further the input is from the origin. For example, `\forall n \in \mathbb{Z}. \sin{2\pi \cdot n} = 0`, but we get:

```
nix-repl> list.map (n: num.sin (2 * n * num.pi)) (list.range 0 20)
[ 0 -0.0932458 -9143.31 -6.20918e+06 -5.68187e+08 -1.7913e+10 -2.92832e+11 -3.06743e+12 -2.32908e+13 -1.38603e+14 -6.81391e+14 -2.87211e+15 -1.06664e+16 -3.56274e+16 -1.08745e+17 -3.07156e+17 -8.10998e+17 -2.01825e+18 -4.76633e+18 -1.0743e+19 -2.32216e+19 ]
```

The obvious solution is to add some multiple of `2\pi` to get the input in `(-\pi, \pi]` or equivalent.

**Comment by kanwren** [comment]
By the way, trig functions are notoriously hard to do and even harder when you have no access to the representation. https://github.com/freemint/fdlibm has a bunch of implementations that can give you a good general idea, though.

**Comment by chessai** [comment]
one day nix will be used in hpc, just as eelco intended
