### ISSUE TITLE
round function outputs float rather than int

### ISSUE THREAD

**Issue by PAI5REECHO** [chessai/nix-std#47]
```nix
        (lib.debug.traceVal
            (builtins.typeOf
              (std.num.round
                32000 * 1.5)))
...
trace: float
```

**Comment by chessai** [comment]
Would you like to submit a PR tofix?

**Comment by chessai** [comment]
actually, i can't reproduce
```
nix-repl> :lf .
Added 13 variables.

nix-repl> std = lib

nix-repl> builtins.typeOf (std.num.round (32000 * 1.5))
"int"
```

**Comment by kanwren** [comment]
I think the original code is just missing parentheses; it says `std.num.round 32000 * 1.5` instead of `std.num.round (32000 * 1.5)`. An int times a float is a float, which is expected behavior.

**Comment by chessai** [comment]
> I think the original code is just missing parentheses; it says `std.num.round 32000 * 1.5` instead of `std.num.round (32000 * 1.5)`. An int times a float is a float, which is expected behavior.

bruh
